<?php


namespace App\Controller;
use App\Controller\AppController;


class HomeController extends  AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('mainlayout');
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('auth',[
            'authenticate' => [
                'form' =>[
                    'fields' => [
                        'username' => 'username',
                        'password' => 'password'
                    ]
                ]
            ],
            'loginAction' => [
                'controller' => 'Home',
                'action' => 'login'
            ]
        ]);
    }

    public function registration()
    {

    }

    public function login()
    {
        echo 'login page';
    }

     public function index()
    {
        echo 'home page';
    }
}

