<?php


namespace App\Controller;

use App\Controller\AppController;
use Cake\Routing\Router;


class TestController extends  AppController
{
    private  $url;
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        $this->url = Router::url();
        $this->viewBuilder()->layout('mainlayout');
    }

    public function index()
    {
        $url = $this->url;
        $this->set($url);
        $this->set('title','Something is better than nothing');
    }

    public function about()
    {
        $arr = [

            'name' => 'Ariful Islam',
            'mobile' => '01750-840217',
            'email' => 'arifsofg@gmail.com'
        ];

        $this->set('title','Title Here');
    }

    public function beta()
    {

    }

}
