<?php


namespace App\Controller;

use App\Controller\AppController;


class TestController extends  AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->viewBuilder('mainlayout');
    }

    public function index()
    {
        $this->set('title','Something is better than nothing');

    }

    public function about()
    {

    }

    public function beta()
    {

    }

}
